language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t hen2864/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true hen2864/docker-react npm run test
    
